name: Workflow for Codecov Action
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Run tests and collect coverage
        run: go test -short -coverprofile=coverage.txt -covermode=atomic ./...
      - name: Upload coverage to Codecov (script)
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.txt
          flags: unittests